// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPPY1qggcMkR5Ccyy-aRAZKroZGIbctUs',
    appId: '1:772365907510:web:db77368a37342e46bd0a97',
    messagingSenderId: '772365907510',
    projectId: 'flutter-litera',
    authDomain: 'flutter-litera.firebaseapp.com',
    storageBucket: 'flutter-litera.firebasestorage.app',
    measurementId: 'G-MBP1Y6EQ9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtaEfot745kC7IP8e_psy8ETDi2-AjRZw',
    appId: '1:772365907510:android:e92be7c969f77484bd0a97',
    messagingSenderId: '772365907510',
    projectId: 'flutter-litera',
    storageBucket: 'flutter-litera.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZEe-gwSBVrkHtGFEaPokyyAWWIjDrLUk',
    appId: '1:772365907510:ios:49c41895eeb562d8bd0a97',
    messagingSenderId: '772365907510',
    projectId: 'flutter-litera',
    storageBucket: 'flutter-litera.firebasestorage.app',
    iosBundleId: 'com.example.flutterLitera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZEe-gwSBVrkHtGFEaPokyyAWWIjDrLUk',
    appId: '1:772365907510:ios:49c41895eeb562d8bd0a97',
    messagingSenderId: '772365907510',
    projectId: 'flutter-litera',
    storageBucket: 'flutter-litera.firebasestorage.app',
    iosBundleId: 'com.example.flutterLitera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPPY1qggcMkR5Ccyy-aRAZKroZGIbctUs',
    appId: '1:772365907510:web:85348fe229c6c038bd0a97',
    messagingSenderId: '772365907510',
    projectId: 'flutter-litera',
    authDomain: 'flutter-litera.firebaseapp.com',
    storageBucket: 'flutter-litera.firebasestorage.app',
    measurementId: 'G-MEV786DK48',
  );
}
