name: Build & Distribute Android App

on:
  push:
    branches: [deployment]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload to Firebase App Distribution
        run: |
          npm install -g firebase-tools
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app 1:772365907510:android:e92be7c969f77484bd0a97 \
            --token ${{ secrets.FIREBASE_TOKEN }} \
            --groups "testers"
